--------------------------------------------------------
--  File created - Sunday-June-01-2025   
--------------------------------------------------------
DROP TABLE "INSURANCE_ADMIN"."ASSETINSURANCE";
DROP TABLE "INSURANCE_ADMIN"."NOTIFICATION_LOG";
DROP TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE";
DROP TABLE "INSURANCE_ADMIN"."STAFFINSURANCE";
DROP TABLE "INSURANCE_ADMIN"."USERS";
DROP TABLE "INSURANCE_ADMIN"."USERS";
DROP TABLE "INSURANCE_ADMIN"."STAFFINSURANCE";
DROP TABLE "INSURANCE_ADMIN"."ASSETINSURANCE";
DROP TABLE "INSURANCE_ADMIN"."NOTIFICATION_LOG";
DROP TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE";
--------------------------------------------------------
--  DDL for Table ASSETINSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSET_TYPE" VARCHAR2(255 BYTE), 
	"ESTIMATED_VALUE" NUMBER, 
	"SUM_INSURED" NUMBER, 
	"NET_PREMIUM" NUMBER, 
	"INSURED_ON" DATE, 
	"EXPIRED_ON" DATE, 
	"POLICY_TYPE" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(255 BYTE), 
	"CO_BENEFICIARY" CHAR(3 BYTE), 
	"PLATE_NO" VARCHAR2(50 BYTE), 
	"VEHICLE_MODEL" VARCHAR2(255 BYTE), 
	"CHASSIS_NO" VARCHAR2(255 BYTE), 
	"ENGINE_NUMBER" VARCHAR2(255 BYTE), 
	"YEAR_OF_MAKE" NUMBER, 
	"ENGINE_CAPACITY" NUMBER, 
	"PREVIOUS_INSURED_VALUE" NUMBER, 
	"PREMIUM_AMOUNT" NUMBER, 
	"INSURANCE_STATUS" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(500 BYTE), 
	"STAFF_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'unauthorized', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION_LOG
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."NOTIFICATION_LOG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MODULE" VARCHAR2(50 BYTE), 
	"RECORD_ID" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"MONTHS_LEFT" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"SENT_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECTINSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"BORROWER_NAME" VARCHAR2(255 BYTE), 
	"LOAN_APPROVED" NUMBER, 
	"COLLATERAL_TYPE" VARCHAR2(255 BYTE), 
	"COLLATERAL_VALUE" NUMBER, 
	"SUM_INSURED" NUMBER, 
	"INSURANCE_PREMIUM" NUMBER, 
	"INSURED_ON" DATE, 
	"EXPIRED_ON" DATE, 
	"POLICY_TYPES" VARCHAR2(255 BYTE), 
	"COMPANY" VARCHAR2(255 BYTE), 
	"CO_BENEFICIARY" CHAR(3 BYTE), 
	"PLATE_NO" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(500 BYTE), 
	"ASSET_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'UNAUTHORIZED', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE, 
	"WORK_UNIT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFFINSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FULL_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"LOAN_AMOUNT" NUMBER, 
	"LOAN_TYPE" VARCHAR2(50 BYTE), 
	"SUM_INSURED" NUMBER, 
	"PREMIUM_AMOUNT" NUMBER, 
	"INSURED_ON" DATE, 
	"EXPIRED_ON" DATE, 
	"POLICY_TYPE" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(255 BYTE), 
	"CO_BENEFICIARY" CHAR(3 BYTE), 
	"REMARK" VARCHAR2(500 BYTE), 
	"USER_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'unauthorized', 
	"AUTHORIZER_ID" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."USERS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"WORK_UNIT" VARCHAR2(255 BYTE), 
	"ROLES" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."USERS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"WORK_UNIT" VARCHAR2(255 BYTE), 
	"ROLES" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFFINSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FULL_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"LOAN_AMOUNT" NUMBER, 
	"LOAN_TYPE" VARCHAR2(50 BYTE), 
	"SUM_INSURED" NUMBER, 
	"PREMIUM_AMOUNT" NUMBER, 
	"INSURED_ON" DATE, 
	"EXPIRED_ON" DATE, 
	"POLICY_TYPE" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(255 BYTE), 
	"CO_BENEFICIARY" CHAR(3 BYTE), 
	"REMARK" VARCHAR2(500 BYTE), 
	"USER_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'unauthorized', 
	"AUTHORIZER_ID" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASSETINSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSET_TYPE" VARCHAR2(255 BYTE), 
	"ESTIMATED_VALUE" NUMBER, 
	"SUM_INSURED" NUMBER, 
	"NET_PREMIUM" NUMBER, 
	"INSURED_ON" DATE, 
	"EXPIRED_ON" DATE, 
	"POLICY_TYPE" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(255 BYTE), 
	"CO_BENEFICIARY" CHAR(3 BYTE), 
	"PLATE_NO" VARCHAR2(50 BYTE), 
	"VEHICLE_MODEL" VARCHAR2(255 BYTE), 
	"CHASSIS_NO" VARCHAR2(255 BYTE), 
	"ENGINE_NUMBER" VARCHAR2(255 BYTE), 
	"YEAR_OF_MAKE" NUMBER, 
	"ENGINE_CAPACITY" NUMBER, 
	"PREVIOUS_INSURED_VALUE" NUMBER, 
	"PREMIUM_AMOUNT" NUMBER, 
	"INSURANCE_STATUS" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(500 BYTE), 
	"STAFF_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'unauthorized', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION_LOG
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."NOTIFICATION_LOG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MODULE" VARCHAR2(50 BYTE), 
	"RECORD_ID" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"MONTHS_LEFT" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"SENT_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECTINSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"BORROWER_NAME" VARCHAR2(255 BYTE), 
	"LOAN_APPROVED" NUMBER, 
	"COLLATERAL_TYPE" VARCHAR2(255 BYTE), 
	"COLLATERAL_VALUE" NUMBER, 
	"SUM_INSURED" NUMBER, 
	"INSURANCE_PREMIUM" NUMBER, 
	"INSURED_ON" DATE, 
	"EXPIRED_ON" DATE, 
	"POLICY_TYPES" VARCHAR2(255 BYTE), 
	"COMPANY" VARCHAR2(255 BYTE), 
	"CO_BENEFICIARY" CHAR(3 BYTE), 
	"PLATE_NO" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(500 BYTE), 
	"ASSET_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'UNAUTHORIZED', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE, 
	"WORK_UNIT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into INSURANCE_ADMIN.ASSETINSURANCE
SET DEFINE OFF;
Insert into INSURANCE_ADMIN.ASSETINSURANCE (ID,ASSET_TYPE,ESTIMATED_VALUE,SUM_INSURED,NET_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPE,COMPANY,CO_BENEFICIARY,PLATE_NO,VEHICLE_MODEL,CHASSIS_NO,ENGINE_NUMBER,YEAR_OF_MAKE,ENGINE_CAPACITY,PREVIOUS_INSURED_VALUE,PREMIUM_AMOUNT,INSURANCE_STATUS,,STAFF_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT) values (1,'automobile',100000,70000,10000,to_date('26-MAY-25','DD-MON-RR'),to_date('26-SEP-25','DD-MON-RR'),'idk','4 killo','YES',null,null,null,null,null,null,null,null,null,null,null,41,'UNAUTHORIZED',to_date('26-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'));
Insert into INSURANCE_ADMIN.ASSETINSURANCE (ID,ASSET_TYPE,ESTIMATED_VALUE,SUM_INSURED,NET_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPE,COMPANY,CO_BENEFICIARY,PLATE_NO,VEHICLE_MODEL,CHASSIS_NO,ENGINE_NUMBER,YEAR_OF_MAKE,ENGINE_CAPACITY,PREVIOUS_INSURED_VALUE,PREMIUM_AMOUNT,INSURANCE_STATUS,,STAFF_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT) values (4,'automobile8',10000,10000,70000,to_date('26-MAY-25','DD-MON-RR'),to_date('26-AUG-25','DD-MON-RR'),'idk','insurance company',null,null,null,null,null,null,null,null,null,null,null,null,41,'UNAUTHORIZED',to_date('26-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'));
REM INSERTING into INSURANCE_ADMIN.NOTIFICATION_LOG
SET DEFINE OFF;
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (21,'STAFF',41,'blackman@gmail.com',3,'Sent',to_timestamp('31-MAY-25 07.25.05.816000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (22,'STAFF',41,'staffauhtorizer@example.com',3,'Sent',to_timestamp('31-MAY-25 07.25.09.215000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (23,'STAFF',41,'blackman@gmail.com',3,'Skipped (Duplicate)',to_timestamp('31-MAY-25 07.43.45.212000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (24,'STAFF',41,'staffauhtorizer@example.com',3,'Skipped (Duplicate)',to_timestamp('31-MAY-25 07.43.45.281000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (25,'STAFF',42,'amanuel62denu@gmail.com',3,'Sent',to_timestamp('31-MAY-25 07.43.48.281000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (26,'STAFF',42,'staffauhtorizer@example.com',3,'Sent',to_timestamp('31-MAY-25 07.43.51.289000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (2,'PROJECT',42,'backa7892@gmail.com',3,'Sent',to_timestamp('26-MAY-25 08.00.09.087000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (3,'PROJECT',42,'projectauhtorizer@example.com',3,'Sent',to_timestamp('26-MAY-25 08.00.13.617000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (4,'PROJECT',42,'backa7892@gmail.com',3,'Failed: connect ETIMEDOUT 173.194.69.109:465',to_timestamp('26-MAY-25 08.00.21.332000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (5,'PROJECT',42,'projectauhtorizer@example.com',3,'Skipped (Duplicate)',to_timestamp('26-MAY-25 08.00.21.383000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (6,'PROJECT',41,'backa7892@gmail.com',1,'Sent',to_timestamp('26-MAY-25 08.00.22.802000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (7,'PROJECT',41,'backa7892@gmail.com',1,'Sent',to_timestamp('26-MAY-25 08.00.49.505000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (8,'PROJECT',41,'projectauhtorizer@example.com',1,'Sent',to_timestamp('26-MAY-25 08.00.50.211000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (9,'PROJECT',41,'projectauhtorizer@example.com',1,'Sent',to_timestamp('26-MAY-25 08.00.53.874000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (10,'ASSET',4,'assetinputter@example.com',3,'Sent',to_timestamp('26-MAY-25 08.00.55.687000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (11,'ASSET',4,'assetinputter@example.com',3,'Sent',to_timestamp('26-MAY-25 08.00.59.584000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (12,'ASSET',4,'assetauhtorizer@example.com',3,'Sent',to_timestamp('26-MAY-25 08.01.00.487000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (13,'ASSET',4,'assetauhtorizer@example.com',3,'Sent',to_timestamp('26-MAY-25 08.01.09.811000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INSURANCE_ADMIN.NOTIFICATION_LOG (ID,MODULE,RECORD_ID,EMAIL,MONTHS_LEFT,STATUS,SENT_AT) values (1,'PROJECT',41,'backa7892@gmail.com',1,'Sent',to_timestamp('26-MAY-25 12.31.59.324000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into INSURANCE_ADMIN.PROJECTINSURANCE
SET DEFINE OFF;
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (1,'abebe',10000,'auto mobile ',10000,10000,11000,to_date('22-MAY-25','DD-MON-RR'),to_date('24-MAR-26','DD-MON-RR'),'i dont lnow','hkifiya','YES','100','test',null,null,'Authorized',to_date('21-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (24,'abe kebe12',10000,'sucking',80000,70000,70000,to_date('22-MAY-25','DD-MON-RR'),to_date('23-NOV-25','DD-MON-RR'),'i dont lnow','insurance company','YES','42',null,null,null,'PENDING',to_date('22-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (25,'another',10000,'type',10000,90000,10000,to_date('22-MAY-25','DD-MON-RR'),to_date('22-NOV-25','DD-MON-RR'),'i dont lnow','4 killo','NO ',null,null,null,null,'Authorized',to_date('22-MAY-25','DD-MON-RR'),to_date('01-JUN-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (26,'bura',10000,'type shit',80000,70000,120000,to_date('23-MAY-25','DD-MON-RR'),to_date('23-AUG-25','DD-MON-RR'),'i dont lnow',null,'NO ',null,null,null,null,'UNAUTHORIZED',to_date('22-MAY-25','DD-MON-RR'),to_date('01-JUN-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (27,'future',10000,'nah',50000,10000,80000,to_date('22-MAY-25','DD-MON-RR'),to_date('22-NOV-25','DD-MON-RR'),null,null,null,null,null,null,22,null,to_date('22-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (28,'past',1000,'type',90000,70000,null,to_date('22-MAY-25','DD-MON-RR'),to_date('22-AUG-25','DD-MON-RR'),null,null,null,null,null,null,null,null,to_date('22-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (29,'abe kebe12',90000,'auto mobile ',null,null,null,to_date('22-MAY-25','DD-MON-RR'),to_date('22-JUN-25','DD-MON-RR'),null,null,null,null,null,null,22,null,to_date('22-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (30,'gang',1000,null,null,null,null,to_date('22-MAY-25','DD-MON-RR'),to_date('22-AUG-25','DD-MON-RR'),null,null,null,null,null,null,22,null,to_date('22-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (42,'balack',10000,'typeish',420000,500000,90000,to_date('26-MAY-25','DD-MON-RR'),to_date('26-AUG-25','DD-MON-RR'),null,null,null,null,null,null,22,'PENDING',to_date('26-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (61,'another',12000,'j jona',14000,2000,10000,to_date('31-MAY-25','DD-MON-RR'),to_date('30-JUL-25','DD-MON-RR'),null,null,null,null,null,null,46,'PENDING',to_date('31-MAY-25','DD-MON-RR'),to_date('31-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (43,'abebe',12000,'bruh',10000,70000,500000,to_date('26-MAY-25','DD-MON-RR'),to_date('26-JUL-25','DD-MON-RR'),'i dont lnow','insurance company','YES',null,null,null,47,'PENDING',to_date('26-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Crop Production Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (21,'tests',10000,'i dont know',20000,80000,900000,to_date('22-AUG-24','DD-MON-RR'),to_date('22-AUG-25','DD-MON-RR'),'i dont lnow','insurance company','YES',null,null,null,null,null,to_date('22-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
Insert into INSURANCE_ADMIN.PROJECTINSURANCE (ID,BORROWER_NAME,LOAN_APPROVED,COLLATERAL_TYPE,COLLATERAL_VALUE,SUM_INSURED,INSURANCE_PREMIUM,INSURED_ON,EXPIRED_ON,POLICY_TYPES,COMPANY,CO_BENEFICIARY,PLATE_NO,,ASSET_ID,USER_ID,STATUS,CREATED_AT,UPDATED_AT,WORK_UNIT) values (41,'adanech',10000,'tyshit',90000,2000,366666,to_date('26-MAY-25','DD-MON-RR'),to_date('26-JUN-25','DD-MON-RR'),null,null,'NO ',null,'test days again',null,22,null,to_date('26-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'),'Chemicals and Pharmaceuticals Directorate');
REM INSERTING into INSURANCE_ADMIN.STAFFINSURANCE
SET DEFINE OFF;
Insert into INSURANCE_ADMIN.STAFFINSURANCE (ID,FULL_NAME,EMAIL,LOAN_AMOUNT,LOAN_TYPE,SUM_INSURED,PREMIUM_AMOUNT,INSURED_ON,EXPIRED_ON,POLICY_TYPE,COMPANY,CO_BENEFICIARY,,USER_ID,STATUS,AUTHORIZER_ID,CREATED_AT,UPDATED_AT) values (41,'block me nig','blackman@gmail.com',10000,'i dont know',120000,300000,to_date('01-JUN-25','DD-MON-RR'),to_date('31-AUG-25','DD-MON-RR'),'idk','Brick house','NO ',null,null,'Authorized',null,to_date('31-MAY-25','DD-MON-RR'),to_date('01-JUN-25','DD-MON-RR'));
Insert into INSURANCE_ADMIN.STAFFINSURANCE (ID,FULL_NAME,EMAIL,LOAN_AMOUNT,LOAN_TYPE,SUM_INSURED,PREMIUM_AMOUNT,INSURED_ON,EXPIRED_ON,POLICY_TYPE,COMPANY,CO_BENEFICIARY,,USER_ID,STATUS,AUTHORIZER_ID,CREATED_AT,UPDATED_AT) values (42,'amanuel','amanuel62denu@gmail.com',10000,'type shit',20000,14000,to_date('31-MAY-25','DD-MON-RR'),to_date('30-AUG-25','DD-MON-RR'),'idk','AAU','YES','this is a test',23,'Authorized',null,to_date('31-MAY-25','DD-MON-RR'),to_date('31-MAY-25','DD-MON-RR'));
Insert into INSURANCE_ADMIN.STAFFINSURANCE (ID,FULL_NAME,EMAIL,LOAN_AMOUNT,LOAN_TYPE,SUM_INSURED,PREMIUM_AMOUNT,INSURED_ON,EXPIRED_ON,POLICY_TYPE,COMPANY,CO_BENEFICIARY,,USER_ID,STATUS,AUTHORIZER_ID,CREATED_AT,UPDATED_AT) values (21,'johny boi34','johniboi34@gmail.com',130000,'i dont know',10000,10000,to_date('26-MAY-25','DD-MON-RR'),to_date('26-JUL-25','DD-MON-RR'),'idk','Brick house',null,null,23,'Authorized',null,to_date('26-MAY-25','DD-MON-RR'),to_date('26-MAY-25','DD-MON-RR'));
Insert into INSURANCE_ADMIN.STAFFINSURANCE (ID,FULL_NAME,EMAIL,LOAN_AMOUNT,LOAN_TYPE,SUM_INSURED,PREMIUM_AMOUNT,INSURED_ON,EXPIRED_ON,POLICY_TYPE,COMPANY,CO_BENEFICIARY,,USER_ID,STATUS,AUTHORIZER_ID,CREATED_AT,UPDATED_AT) values (1,'johny boi','johniboi@gmail.com',1000,'i dont know',10000,10000,to_date('23-MAY-25','DD-MON-RR'),to_date('25-FEB-26','DD-MON-RR'),'idk','Brick house',null,null,null,'Authorized',null,to_date('22-MAY-25','DD-MON-RR'),to_date('01-JUN-25','DD-MON-RR'));
REM INSERTING into INSURANCE_ADMIN.USERS
SET DEFINE OFF;
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (1,'projectinputter@example.com','$2b$10$MfoVpnIs57HD4IpGnmDljuLt4zMYcWawWHkqQzR9C9Aur8olgb7K2',null,'Project Insurance Unit','PROJECT-INPUTTER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (22,'backa7892@gmail.com','$2b$10$0idQtvEePOZQor8tRB7kFeolfuSq5GlOp.yfMQvS/oQf0bDqbWQpG',null,'Project Insurance Unit','PROJECT-INPUTTER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (41,'assetinputter@example.com','$2b$10$VJWyFQKYujUTlvBpbtI2WORPIO6eBtbSQ911h9YiLs1mRS/D09156',null,'Project Insurance Unit','ASSET-INPUTTER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (42,'projectauhtorizer@example.com','$2b$10$7.7kCOUkacDmhxxuy3nRqOiauRIqEp3s7I2S82a5WunAUPGlH1Tpu',null,'Project Insurance Unit','PROJECT-AUTHORIZER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (43,'staffauhtorizer@example.com','$2b$10$tkvcSmCIrtLmBxp.tGS5Fu5GA1O93Hgix2t37IEeLsqFEzz9vDXhS',null,'Project Insurance Unit','STAFF-AUTHORIZER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (44,'assetauhtorizer@example.com','$2b$10$nIqpmwfYeG5ki9MuwOTu4OdMvkF9CV.ToUBDAS5XH4FL2RQwJO4nW',null,'Project Insurance Unit','ASSET-AUTHORIZER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (48,'projectauthorizer23@example.com','$2b$10$/O8hpUXJNSzX6EYp38HDD.3y6YL5sP1VYa.8HsOuQoshorpML5gkC',null,'Chemicals and Pharmaceuticals Directorate','PROJECT-INPUTTER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (49,'projectauthorizer03@example.com','$2b$10$LXUt9E95GcI70ia2cfDbeOuJd4YehvkSAr99Zfpzunqg8PoDWefZq',null,'Chemicals and Pharmaceuticals Directorate','PROJECT-AUTHORIZER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (50,'staffviewer@example.com','$2b$10$A0EBgf/UbfleH6y2r2Jq5uCriXlbl9GvoVhG3boXsjM.QZAMh7XYO',null,'Chemicals and Pharmaceuticals Directorate','VIEWER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (51,'assetviewer@example.com','$2b$10$v3c70t5mPqUW4lQ8fq5poe1QYisSiJY/ebO/PdqadWOMzwa.tWWim',null,'asset work_unit','VIEWER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (23,'staffinputter@example.com','$2b$10$G2XJUGuJ1YNrrEWzhaEwLe6mfSWhlr1O7tMyralvVQsa6QDV4zYuu',null,'Staff Insurance Unit','STAFF-INPUTTER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (45,'projectauthorizer12@example.com','$2b$10$RL7depgPZMnUnYh4Fq4qbe/oILRdgoBRkJj6zOqjVmGk/y7leCLC2',null,'Project Insurance Unit','PROJECT-AUTHORIZER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (21,'buraaman20@gmail.com','$2b$10$fWctQU5p8C9DeKZnBAVbq.Pmftqzbh6w9XPgRaE9niOafPG3p29sy',null,'Project Insurance Unit','PROJECT-INPUTTER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (46,'projectinputter23@example.com','$2b$10$E1/qJzdIG7qMhiBZxSWEBefi32quRWdcApXprwt4gdCXSdZ17Llai',null,'Chemicals and Pharmaceuticals Directorate','PROJECT-INPUTTER');
Insert into INSURANCE_ADMIN.USERS (ID,EMAIL,PASSWORD,STATUS,WORK_UNIT,ROLES) values (47,'projectinputter234@example.com','$2b$10$.XqvqABExJZ04l9QpxM6ue78EKFSFObSSIT7/Ylx9cdOOqUvUtLpu',null,'Crop Production Directorate','PROJECT-INPUTTER');
--------------------------------------------------------
--  DDL for Index SYS_C008272
--------------------------------------------------------

  CREATE UNIQUE INDEX "INSURANCE_ADMIN"."SYS_C008272" ON "INSURANCE_ADMIN"."ASSETINSURANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008327
--------------------------------------------------------

  CREATE UNIQUE INDEX "INSURANCE_ADMIN"."SYS_C008327" ON "INSURANCE_ADMIN"."NOTIFICATION_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "INSURANCE_ADMIN"."SYS_C008279" ON "INSURANCE_ADMIN"."PROJECTINSURANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008260
--------------------------------------------------------

  CREATE UNIQUE INDEX "INSURANCE_ADMIN"."SYS_C008260" ON "INSURANCE_ADMIN"."STAFFINSURANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008261
--------------------------------------------------------

  CREATE UNIQUE INDEX "INSURANCE_ADMIN"."SYS_C008261" ON "INSURANCE_ADMIN"."STAFFINSURANCE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008289
--------------------------------------------------------

  CREATE UNIQUE INDEX "INSURANCE_ADMIN"."SYS_C008289" ON "INSURANCE_ADMIN"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008290
--------------------------------------------------------

  CREATE UNIQUE INDEX "INSURANCE_ADMIN"."SYS_C008290" ON "INSURANCE_ADMIN"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ASSETINSURANCE_UPDATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSURANCE_ADMIN"."ASSETINSURANCE_UPDATE_TRIGGER" 
BEFORE UPDATE ON ASSETINSURANCE
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;

/
ALTER TRIGGER "INSURANCE_ADMIN"."ASSETINSURANCE_UPDATE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECTINSURANCE_UPDATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSURANCE_ADMIN"."PROJECTINSURANCE_UPDATE_TRIGGER" 
BEFORE UPDATE ON PROJECTINSURANCE
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;

/
ALTER TRIGGER "INSURANCE_ADMIN"."PROJECTINSURANCE_UPDATE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STAFFINSURANCE_UPDATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSURANCE_ADMIN"."STAFFINSURANCE_UPDATE_TRIGGER" 
BEFORE UPDATE ON STAFFINSURANCE
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;

/
ALTER TRIGGER "INSURANCE_ADMIN"."STAFFINSURANCE_UPDATE_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSETINSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("ASSET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("ESTIMATED_VALUE" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("NET_PREMIUM" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("INSURED_ON" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("EXPIRED_ON" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("POLICY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" ADD CHECK (co_beneficiary IN ('YES', 'NO')) ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" ADD CHECK (insurance_status IN ('Renewed', 'Expired', 'Cancelled')) ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION_LOG
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."NOTIFICATION_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."NOTIFICATION_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECTINSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" MODIFY ("BORROWER_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" MODIFY ("LOAN_APPROVED" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" MODIFY ("INSURED_ON" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" MODIFY ("EXPIRED_ON" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" ADD CHECK (co_beneficiary IN ('YES', 'NO')) ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" ADD CONSTRAINT "CHK_PROJECTINSURANCE_WORK_UNIT" CHECK (WORK_UNIT IN (
            'Chemicals and Pharmaceuticals Directorate',
            'Crop Production Directorate',
            'Food and Agro-Processing Directorate',
            'Horticulture and Forestry Directorate',
            'Livestock Directorate',
            'Mining, Energy and Construction Directorate',
            'Poultry Directorate',
            'Textile and Leather Directorate',
            'Wood, Metals and Others Directorate'
    )) ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFFINSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("LOAN_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("LOAN_TYPE" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("INSURED_ON" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("EXPIRED_ON" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("POLICY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" ADD CHECK (co_beneficiary IN ('YES', 'NO')) ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" MODIFY ("PREMIUM_AMOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."USERS" MODIFY ("ROLES" NOT NULL ENABLE);
  ALTER TABLE "INSURANCE_ADMIN"."USERS" ADD CHECK (STATUS IN ('active', 'inactive')) ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSETINSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" ADD CONSTRAINT "FK_STAFF" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "INSURANCE_ADMIN"."STAFFINSURANCE" ("ID") ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."ASSETINSURANCE" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "INSURANCE_ADMIN"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECTINSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" ADD CONSTRAINT "FK_ASSET" FOREIGN KEY ("ASSET_ID")
	  REFERENCES "INSURANCE_ADMIN"."ASSETINSURANCE" ("ID") ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."PROJECTINSURANCE" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "INSURANCE_ADMIN"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFFINSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "INSURANCE_ADMIN"."USERS" ("ID") ENABLE;
  ALTER TABLE "INSURANCE_ADMIN"."STAFFINSURANCE" ADD CONSTRAINT "FK_STAFFINSURANCE_AUTHORIZER" FOREIGN KEY ("AUTHORIZER_ID")
	  REFERENCES "INSURANCE_ADMIN"."USERS" ("ID") ENABLE;
